### ISSUE TITLE
The BFF sample does not work as is.

### ISSUE THREAD

**Issue by edcurate** [DuendeSoftware/Samples#70]
Hello,

I am getting the exception from the BFF part (IdentityServer\v6\Quickstarts\6_JS_with_backend) of
https://github.com/DuendeSoftware/Samples.git  
No changes just trying to checkout the BFF working.

![image](https://user-images.githubusercontent.com/103842461/182018194-96004a04-8317-4b53-8770-83a72c8d75db.png)

**Comment by josephdecock** [comment]
Hi @edcurate, 

This error can happen if the IdentityServer host is not running. The BFF tries to connect to the IdentityServer host on startup to retrieve protocol configuration and metadata (from the discovery endpoint). If the IdentityServer host is not running, that will fail.

There are actually 3 projects to run: the BFF (JavaScriptClient project in the solution), an API for it to call (the Api project), and an IdentityServer host to issue tokens (the IdentityServer project). To run the full demo, you need to run all 3 projects. You can run each project separately (right click on project in Sln explorer -> Debug -> Start New Instance). If you run this way, be sure to start IdentityServer first, so that the other projects can successfully do discovery when they startup.

Alternatively, you can configure the solution to run all the projects on startup (right click on the solution -> Set Startup Projects -> set the startup projects as follows).

![image](https://user-images.githubusercontent.com/1145533/182038671-aef41085-0911-4e12-8a5a-58da5f6191b4.png)

**Comment by edcurate** [comment]
I can confirm the identity server is running. And i see below message logged as well.

![image](https://user-images.githubusercontent.com/103842461/182039406-b01b83b4-5854-4a8d-bf91-c0031b38e778.png)

**Comment by josephdecock** [comment]
Hmm, that's odd. Can you please double check that you have the latest code and no local changes? What's the output of `git log -n 1` and `git status`?

**Comment by edcurate** [comment]
No local changes.. except that i made sln files for debugging purpose..  for a diff sample 
![image](https://user-images.githubusercontent.com/103842461/182039881-cd7f434f-f013-47fb-9144-73ff67e4e6df.png)

**Comment by josephdecock** [comment]
Hmm, this is strange. What is in the ReactIdentity directory?

**Comment by josephdecock** [comment]
Oh, nevermind, I'm just realizing that I'm looking at a different sample than you! Stand by...

**Comment by josephdecock** [comment]
Okay, I was confused momentarily by your changes in the other samples, but now I see what you're doing. Let's gather some more diagnostic info. Please do the following: 
Make sure nothing is running
- Start just the IdentityServer project (right click on it in sln explorer -> Debug -> start new instance)
- Go to https://localhost:5001/.well-known/openid-configuration in your browser, share the output here.
- Now start the Api Project (again with the sln explorer menu)
- Go to https://localhost:6001/swagger/index.html, and let us know what you see (should be swagger for one api endpoint at /identity)
- Now start the JavaScriptClient project
- This should open your browser to https://localhost:5003/. Does that happen? If so, what do you see?

Also helpful might be more of the ouput logged by identityserver immediately before and after the error.

Thanks in advance for any more details you can provide!

Joe

**Comment by josephdecock** [comment]
@edcurate, nevermind, no need for more diagnostics - the issue is that this quickstart is assuming you've done the previous quickstarts and set up integration with google. I'm updating the sample so that it will work out of the box. You can fix this in your copy by commenting out the call to AddGoogle in the IdentityServer host project.
