### ISSUE TITLE
Get user claims in User Interaction Sample

### ISSUE THREAD

**Issue by VR-Architect** [DuendeSoftware/Samples#78]
If I put a break point on the Get API method and inspect the user claims, it doesn't have the user claims include such as the ones given in the TestUser.cs file.  How do I get to see these on the API method?

```
                    SubjectId = "22",
                    Username = "bob",
                    Password = "bob",
                    Claims =
                    {
                        new Claim(JwtClaimTypes.Name, "Bob Smith"),
                        new Claim(JwtClaimTypes.GivenName, "Bob"),
                        new Claim(JwtClaimTypes.FamilyName, "Smith"),
                        new Claim(JwtClaimTypes.Email, "BobSmith@email.com"),
                        new Claim(JwtClaimTypes.EmailVerified, "true", ClaimValueTypes.Boolean),
                        new Claim(JwtClaimTypes.WebSite, "http://bob.com"),
                        new Claim(JwtClaimTypes.Address, JsonSerializer.Serialize(address), IdentityServerConstants.ClaimValueTypes.Json)
                    }
```

[Profile Service Sample v6](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/UserInteraction/ProfileService )

**Comment by josephdecock** [comment]
You're not seeing these claims in the API because access tokens don't include profile information by default. That information is typically retrieved from the user info endpoint in the client application. Most APIs don't need more than the user's id (which is present in the sub claim), and scopes. In some circumstances, you might need additional information about the user, and you could store that as claims in the access token. If you need to do that, use the Profile Service, documented [here  ](https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/) and [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/).
